/** 소상공인시장진흥공단 상권업종분류 API 응답에서 생성됨. */
export type IndustryCategory = {
  indsMclsCd: string;
  indsMclsNm: string;
  indsSclsCd: string;
  indsSclsNm: string;
};
export const INDUSTRY_CATEGORIES = [
  {
    indsMclsCd: "G202",
    indsMclsNm: "자동차 부품 소매",
    indsSclsCd: "G20201",
    indsSclsNm: "타이어 소매업",
  },
  {
    indsMclsCd: "G202",
    indsMclsNm: "자동차 부품 소매",
    indsSclsCd: "G20202",
    indsSclsNm: "자동차 부품 소매업",
  },
  {
    indsMclsCd: "G203",
    indsMclsNm: "모터사이클 소매",
    indsSclsCd: "G20301",
    indsSclsNm: "모터사이클 및 부품 소매업",
  },
  { indsMclsCd: "G204", indsMclsNm: "종합 소매", indsSclsCd: "G20404", indsSclsNm: "슈퍼마켓" },
  { indsMclsCd: "G204", indsMclsNm: "종합 소매", indsSclsCd: "G20405", indsSclsNm: "편의점" },
  {
    indsMclsCd: "G204",
    indsMclsNm: "종합 소매",
    indsSclsCd: "G20499",
    indsSclsNm: "그 외 기타 종합 소매업",
  },
  {
    indsMclsCd: "G205",
    indsMclsNm: "식료품 소매",
    indsSclsCd: "G20501",
    indsSclsNm: "곡물/곡분 소매업",
  },
  {
    indsMclsCd: "G205",
    indsMclsNm: "식료품 소매",
    indsSclsCd: "G20502",
    indsSclsNm: "가축 사료 소매업",
  },
  { indsMclsCd: "G205", indsMclsNm: "식료품 소매", indsSclsCd: "G20503", indsSclsNm: "정육점" },
  {
    indsMclsCd: "G205",
    indsMclsNm: "식료품 소매",
    indsSclsCd: "G20504",
    indsSclsNm: "건어물/젓갈 소매업",
  },
  {
    indsMclsCd: "G205",
    indsMclsNm: "식료품 소매",
    indsSclsCd: "G20505",
    indsSclsNm: "수산물 소매업",
  },
  {
    indsMclsCd: "G205",
    indsMclsNm: "식료품 소매",
    indsSclsCd: "G20506",
    indsSclsNm: "채소/과일 소매업",
  },
  {
    indsMclsCd: "G205",
    indsMclsNm: "식료품 소매",
    indsSclsCd: "G20507",
    indsSclsNm: "아이스크림 할인점",
  },
  {
    indsMclsCd: "G205",
    indsMclsNm: "식료품 소매",
    indsSclsCd: "G20508",
    indsSclsNm: "건강보조식품 소매업",
  },
  {
    indsMclsCd: "G205",
    indsMclsNm: "식료품 소매",
    indsSclsCd: "G20509",
    indsSclsNm: "반찬/식료품 소매업",
  },
  { indsMclsCd: "G206", indsMclsNm: "음료 소매", indsSclsCd: "G20601", indsSclsNm: "얼음 소매업" },
  { indsMclsCd: "G206", indsMclsNm: "음료 소매", indsSclsCd: "G20602", indsSclsNm: "주류 소매업" },
  {
    indsMclsCd: "G206",
    indsMclsNm: "음료 소매",
    indsSclsCd: "G20603",
    indsSclsNm: "생수/음료 소매업",
  },
  { indsMclsCd: "G206", indsMclsNm: "음료 소매", indsSclsCd: "G20604", indsSclsNm: "우유 소매업" },
  {
    indsMclsCd: "G207",
    indsMclsNm: "담배 소매",
    indsSclsCd: "G20701",
    indsSclsNm: "담배/전자담배 소매업",
  },
  {
    indsMclsCd: "G208",
    indsMclsNm: "가전·통신 소매",
    indsSclsCd: "G20801",
    indsSclsNm: "컴퓨터/소프트웨어 소매업",
  },
  {
    indsMclsCd: "G208",
    indsMclsNm: "가전·통신 소매",
    indsSclsCd: "G20802",
    indsSclsNm: "핸드폰 소매업",
  },
  {
    indsMclsCd: "G208",
    indsMclsNm: "가전·통신 소매",
    indsSclsCd: "G20803",
    indsSclsNm: "가전제품 소매업",
  },
  {
    indsMclsCd: "G209",
    indsMclsNm: "섬유·의복·신발 소매",
    indsSclsCd: "G20901",
    indsSclsNm: "남성 의류 소매업",
  },
  {
    indsMclsCd: "G209",
    indsMclsNm: "섬유·의복·신발 소매",
    indsSclsCd: "G20902",
    indsSclsNm: "여성 의류 소매업",
  },
  {
    indsMclsCd: "G209",
    indsMclsNm: "섬유·의복·신발 소매",
    indsSclsCd: "G20903",
    indsSclsNm: "유아용 의류 소매업",
  },
  {
    indsMclsCd: "G209",
    indsMclsNm: "섬유·의복·신발 소매",
    indsSclsCd: "G20904",
    indsSclsNm: "한복 소매업",
  },
  {
    indsMclsCd: "G209",
    indsMclsNm: "섬유·의복·신발 소매",
    indsSclsCd: "G20905",
    indsSclsNm: "기타 의류 소매업",
  },
  {
    indsMclsCd: "G209",
    indsMclsNm: "섬유·의복·신발 소매",
    indsSclsCd: "G20906",
    indsSclsNm: "침구류/커튼 소매업",
  },
  {
    indsMclsCd: "G209",
    indsMclsNm: "섬유·의복·신발 소매",
    indsSclsCd: "G20907",
    indsSclsNm: "액세서리/잡화 소매업",
  },
  {
    indsMclsCd: "G209",
    indsMclsNm: "섬유·의복·신발 소매",
    indsSclsCd: "G20908",
    indsSclsNm: "가발 소매업",
  },
  {
    indsMclsCd: "G209",
    indsMclsNm: "섬유·의복·신발 소매",
    indsSclsCd: "G20909",
    indsSclsNm: "실/섬유제품 소매업",
  },
  {
    indsMclsCd: "G209",
    indsMclsNm: "섬유·의복·신발 소매",
    indsSclsCd: "G20910",
    indsSclsNm: "신발 소매업",
  },
  {
    indsMclsCd: "G209",
    indsMclsNm: "섬유·의복·신발 소매",
    indsSclsCd: "G20911",
    indsSclsNm: "가방 소매업",
  },
  {
    indsMclsCd: "G210",
    indsMclsNm: "철물·건설자재 소매",
    indsSclsCd: "G21001",
    indsSclsNm: "철물/공구 소매업",
  },
  {
    indsMclsCd: "G210",
    indsMclsNm: "철물·건설자재 소매",
    indsSclsCd: "G21002",
    indsSclsNm: "벽지/장판/마루 소매업",
  },
  {
    indsMclsCd: "G210",
    indsMclsNm: "철물·건설자재 소매",
    indsSclsCd: "G21003",
    indsSclsNm: "건설/건축자재 소매업",
  },
  {
    indsMclsCd: "G210",
    indsMclsNm: "철물·건설자재 소매",
    indsSclsCd: "G21099",
    indsSclsNm: "기타 건설/건축자재 소매업",
  },
  { indsMclsCd: "G211", indsMclsNm: "가구 소매", indsSclsCd: "G21101", indsSclsNm: "가구 소매업" },
  {
    indsMclsCd: "G212",
    indsMclsNm: "기타 생활용품 소매",
    indsSclsCd: "G21201",
    indsSclsNm: "전기용품/조명장치 소매업",
  },
  {
    indsMclsCd: "G212",
    indsMclsNm: "기타 생활용품 소매",
    indsSclsCd: "G21202",
    indsSclsNm: "주방/가정용품 소매업",
  },
  {
    indsMclsCd: "G212",
    indsMclsNm: "기타 생활용품 소매",
    indsSclsCd: "G21203",
    indsSclsNm: "악기 소매업",
  },
  { indsMclsCd: "G213", indsMclsNm: "오락용품 소매", indsSclsCd: "G21301", indsSclsNm: "서점" },
  {
    indsMclsCd: "G213",
    indsMclsNm: "오락용품 소매",
    indsSclsCd: "G21302",
    indsSclsNm: "문구/회화용품 소매업",
  },
  {
    indsMclsCd: "G213",
    indsMclsNm: "오락용품 소매",
    indsSclsCd: "G21303",
    indsSclsNm: "음반/비디오물 소매업",
  },
  {
    indsMclsCd: "G213",
    indsMclsNm: "오락용품 소매",
    indsSclsCd: "G21304",
    indsSclsNm: "운동용품 소매업",
  },
  {
    indsMclsCd: "G213",
    indsMclsNm: "오락용품 소매",
    indsSclsCd: "G21305",
    indsSclsNm: "자전거 소매업",
  },
  {
    indsMclsCd: "G213",
    indsMclsNm: "오락용품 소매",
    indsSclsCd: "G21306",
    indsSclsNm: "장난감 소매업",
  },
  { indsMclsCd: "G214", indsMclsNm: "연료 소매", indsSclsCd: "G21401", indsSclsNm: "주유소" },
  { indsMclsCd: "G214", indsMclsNm: "연료 소매", indsSclsCd: "G21402", indsSclsNm: "가스 충전소" },
  {
    indsMclsCd: "G214",
    indsMclsNm: "연료 소매",
    indsSclsCd: "G21403",
    indsSclsNm: "가정용 연료 소매업",
  },
  { indsMclsCd: "G215", indsMclsNm: "의약·화장품 소매", indsSclsCd: "G21501", indsSclsNm: "약국" },
  {
    indsMclsCd: "G215",
    indsMclsNm: "의약·화장품 소매",
    indsSclsCd: "G21502",
    indsSclsNm: "의료기기 소매업",
  },
  {
    indsMclsCd: "G215",
    indsMclsNm: "의약·화장품 소매",
    indsSclsCd: "G21503",
    indsSclsNm: "화장품 소매업",
  },
  {
    indsMclsCd: "G216",
    indsMclsNm: "안경·정밀기기 소매",
    indsSclsCd: "G21601",
    indsSclsNm: "사무기기 소매업",
  },
  {
    indsMclsCd: "G216",
    indsMclsNm: "안경·정밀기기 소매",
    indsSclsCd: "G21602",
    indsSclsNm: "안경렌즈 소매업",
  },
  {
    indsMclsCd: "G216",
    indsMclsNm: "안경·정밀기기 소매",
    indsSclsCd: "G21603",
    indsSclsNm: "사진기/기타 광학기기 소매업",
  },
  {
    indsMclsCd: "G217",
    indsMclsNm: "시계·귀금속 소매",
    indsSclsCd: "G21701",
    indsSclsNm: "시계/귀금속 소매업",
  },
  {
    indsMclsCd: "G218",
    indsMclsNm: "장식품 소매",
    indsSclsCd: "G21801",
    indsSclsNm: "예술품 소매업",
  },
  { indsMclsCd: "G218", indsMclsNm: "장식품 소매", indsSclsCd: "G21802", indsSclsNm: "기념품점" },
  { indsMclsCd: "G219", indsMclsNm: "식물 소매", indsSclsCd: "G21901", indsSclsNm: "꽃집" },
  {
    indsMclsCd: "G220",
    indsMclsNm: "애완동물·용품 소매",
    indsSclsCd: "G22001",
    indsSclsNm: "애완동물/애완용품 소매업",
  },
  {
    indsMclsCd: "G221",
    indsMclsNm: "기타 상품 소매",
    indsSclsCd: "G22199",
    indsSclsNm: "그 외 기타 상품 전문 소매업",
  },
  {
    indsMclsCd: "G222",
    indsMclsNm: "중고 상품 소매",
    indsSclsCd: "G22201",
    indsSclsNm: "중고 상품 소매업",
  },
  { indsMclsCd: "I101", indsMclsNm: "일반 숙박", indsSclsCd: "I10101", indsSclsNm: "호텔/리조트" },
  { indsMclsCd: "I101", indsMclsNm: "일반 숙박", indsSclsCd: "I10102", indsSclsNm: "여관/모텔" },
  { indsMclsCd: "I101", indsMclsNm: "일반 숙박", indsSclsCd: "I10103", indsSclsNm: "펜션" },
  { indsMclsCd: "I101", indsMclsNm: "일반 숙박", indsSclsCd: "I10104", indsSclsNm: "캠핑/글램핑" },
  {
    indsMclsCd: "I102",
    indsMclsNm: "기타 숙박",
    indsSclsCd: "I10201",
    indsSclsNm: "기숙사/고시원",
  },
  {
    indsMclsCd: "I102",
    indsMclsNm: "기타 숙박",
    indsSclsCd: "I10299",
    indsSclsNm: "그 외 기타 숙박업",
  },
  { indsMclsCd: "I201", indsMclsNm: "한식", indsSclsCd: "I20101", indsSclsNm: "백반/한정식" },
  { indsMclsCd: "I201", indsMclsNm: "한식", indsSclsCd: "I20102", indsSclsNm: "국/탕/찌개류" },
  { indsMclsCd: "I201", indsMclsNm: "한식", indsSclsCd: "I20103", indsSclsNm: "족발/보쌈" },
  { indsMclsCd: "I201", indsMclsNm: "한식", indsSclsCd: "I20104", indsSclsNm: "전/부침개" },
  { indsMclsCd: "I201", indsMclsNm: "한식", indsSclsCd: "I20105", indsSclsNm: "국수/칼국수" },
  { indsMclsCd: "I201", indsMclsNm: "한식", indsSclsCd: "I20106", indsSclsNm: "냉면/밀면" },
  { indsMclsCd: "I201", indsMclsNm: "한식", indsSclsCd: "I20107", indsSclsNm: "돼지고기 구이/찜" },
  { indsMclsCd: "I201", indsMclsNm: "한식", indsSclsCd: "I20108", indsSclsNm: "소고기 구이/찜" },
  { indsMclsCd: "I201", indsMclsNm: "한식", indsSclsCd: "I20109", indsSclsNm: "곱창 전골/구이" },
  {
    indsMclsCd: "I201",
    indsMclsNm: "한식",
    indsSclsCd: "I20110",
    indsSclsNm: "닭/오리고기 구이/찜",
  },
  { indsMclsCd: "I201", indsMclsNm: "한식", indsSclsCd: "I20111", indsSclsNm: "횟집" },
  { indsMclsCd: "I201", indsMclsNm: "한식", indsSclsCd: "I20112", indsSclsNm: "해산물 구이/찜" },
  { indsMclsCd: "I201", indsMclsNm: "한식", indsSclsCd: "I20113", indsSclsNm: "복 요리 전문" },
  { indsMclsCd: "I201", indsMclsNm: "한식", indsSclsCd: "I20199", indsSclsNm: "기타 한식 음식점" },
  { indsMclsCd: "I202", indsMclsNm: "중식", indsSclsCd: "I20201", indsSclsNm: "중국집" },
  { indsMclsCd: "I202", indsMclsNm: "중식", indsSclsCd: "I20202", indsSclsNm: "마라탕/훠궈" },
  { indsMclsCd: "I203", indsMclsNm: "일식", indsSclsCd: "I20301", indsSclsNm: "일식 회/초밥" },
  {
    indsMclsCd: "I203",
    indsMclsNm: "일식",
    indsSclsCd: "I20302",
    indsSclsNm: "일식 카레/돈가스/덮밥",
  },
  { indsMclsCd: "I203", indsMclsNm: "일식", indsSclsCd: "I20303", indsSclsNm: "일식 면 요리" },
  { indsMclsCd: "I203", indsMclsNm: "일식", indsSclsCd: "I20399", indsSclsNm: "기타 일식 음식점" },
  { indsMclsCd: "I204", indsMclsNm: "서양식", indsSclsCd: "I20401", indsSclsNm: "경양식" },
  { indsMclsCd: "I204", indsMclsNm: "서양식", indsSclsCd: "I20402", indsSclsNm: "파스타/스테이크" },
  { indsMclsCd: "I204", indsMclsNm: "서양식", indsSclsCd: "I20403", indsSclsNm: "패밀리레스토랑" },
  {
    indsMclsCd: "I204",
    indsMclsNm: "서양식",
    indsSclsCd: "I20499",
    indsSclsNm: "기타 서양식 음식점",
  },
  {
    indsMclsCd: "I205",
    indsMclsNm: "동남아시아",
    indsSclsCd: "I20501",
    indsSclsNm: "베트남식 전문",
  },
  {
    indsMclsCd: "I205",
    indsMclsNm: "동남아시아",
    indsSclsCd: "I20599",
    indsSclsNm: "기타 동남아식 전문",
  },
  {
    indsMclsCd: "I206",
    indsMclsNm: "기타 외국",
    indsSclsCd: "I20601",
    indsSclsNm: "분류 안된 외국식 음식점",
  },
  { indsMclsCd: "I207", indsMclsNm: "구내식당·뷔페", indsSclsCd: "I20701", indsSclsNm: "구내식당" },
  { indsMclsCd: "I207", indsMclsNm: "구내식당·뷔페", indsSclsCd: "I20702", indsSclsNm: "뷔페" },
  { indsMclsCd: "I210", indsMclsNm: "기타 간이", indsSclsCd: "I21001", indsSclsNm: "빵/도넛" },
  { indsMclsCd: "I210", indsMclsNm: "기타 간이", indsSclsCd: "I21002", indsSclsNm: "떡/한과" },
  { indsMclsCd: "I210", indsMclsNm: "기타 간이", indsSclsCd: "I21003", indsSclsNm: "피자" },
  { indsMclsCd: "I210", indsMclsNm: "기타 간이", indsSclsCd: "I21004", indsSclsNm: "버거" },
  {
    indsMclsCd: "I210",
    indsMclsNm: "기타 간이",
    indsSclsCd: "I21005",
    indsSclsNm: "토스트/샌드위치/샐러드",
  },
  { indsMclsCd: "I210", indsMclsNm: "기타 간이", indsSclsCd: "I21006", indsSclsNm: "치킨" },
  {
    indsMclsCd: "I210",
    indsMclsNm: "기타 간이",
    indsSclsCd: "I21007",
    indsSclsNm: "김밥/만두/분식",
  },
  {
    indsMclsCd: "I210",
    indsMclsNm: "기타 간이",
    indsSclsCd: "I21008",
    indsSclsNm: "아이스크림/빙수",
  },
  {
    indsMclsCd: "I210",
    indsMclsNm: "기타 간이",
    indsSclsCd: "I21099",
    indsSclsNm: "그 외 기타 간이 음식점",
  },
  { indsMclsCd: "I211", indsMclsNm: "주점", indsSclsCd: "I21101", indsSclsNm: "일반 유흥 주점" },
  { indsMclsCd: "I211", indsMclsNm: "주점", indsSclsCd: "I21102", indsSclsNm: "무도 유흥 주점" },
  { indsMclsCd: "I211", indsMclsNm: "주점", indsSclsCd: "I21103", indsSclsNm: "생맥주 전문" },
  { indsMclsCd: "I211", indsMclsNm: "주점", indsSclsCd: "I21104", indsSclsNm: "요리 주점" },
  { indsMclsCd: "I212", indsMclsNm: "카페", indsSclsCd: "I21201", indsSclsNm: "카페" },
  {
    indsMclsCd: "L102",
    indsMclsNm: "부동산 서비스",
    indsSclsCd: "L10203",
    indsSclsNm: "부동산 중개/대리업",
  },
  { indsMclsCd: "M103", indsMclsNm: "법무관련 ", indsSclsCd: "M10301", indsSclsNm: "변호사" },
  { indsMclsCd: "M103", indsMclsNm: "법무관련 ", indsSclsCd: "M10302", indsSclsNm: "변리사" },
  { indsMclsCd: "M103", indsMclsNm: "법무관련 ", indsSclsCd: "M10303", indsSclsNm: "법무사" },
  { indsMclsCd: "M103", indsMclsNm: "법무관련 ", indsSclsCd: "M10306", indsSclsNm: "행정사" },
  { indsMclsCd: "M103", indsMclsNm: "법무관련 ", indsSclsCd: "M10307", indsSclsNm: "공인노무사" },
  {
    indsMclsCd: "M103",
    indsMclsNm: "법무관련 ",
    indsSclsCd: "M10399",
    indsSclsNm: "기타 법무관련 서비스업",
  },
  { indsMclsCd: "M104", indsMclsNm: "회계·세무", indsSclsCd: "M10401", indsSclsNm: "공인회계사" },
  { indsMclsCd: "M104", indsMclsNm: "회계·세무", indsSclsCd: "M10402", indsSclsNm: "세무사" },
  {
    indsMclsCd: "M104",
    indsMclsNm: "회계·세무",
    indsSclsCd: "M10499",
    indsSclsNm: "기타 회계 관련 서비스업",
  },
  { indsMclsCd: "M105", indsMclsNm: "광고", indsSclsCd: "M10501", indsSclsNm: "광고 대행업" },
  {
    indsMclsCd: "M105",
    indsMclsNm: "광고",
    indsSclsCd: "M10502",
    indsSclsNm: "옥외/전시 광고 대행업",
  },
  { indsMclsCd: "M105", indsMclsNm: "광고", indsSclsCd: "M10503", indsSclsNm: "광고 매체 판매업" },
  {
    indsMclsCd: "M105",
    indsMclsNm: "광고",
    indsSclsCd: "M10504",
    indsSclsNm: "광고물 설계/제작업",
  },
  {
    indsMclsCd: "M105",
    indsMclsNm: "광고",
    indsSclsCd: "M10599",
    indsSclsNm: "기타 광고 관련 서비스업",
  },
  {
    indsMclsCd: "M106",
    indsMclsNm: "시장 조사",
    indsSclsCd: "M10601",
    indsSclsNm: "시장 조사 및 여론 조사업",
  },
  {
    indsMclsCd: "M107",
    indsMclsNm: "본사·경영 컨설팅",
    indsSclsCd: "M10703",
    indsSclsNm: "경영 컨설팅업",
  },
  {
    indsMclsCd: "M109",
    indsMclsNm: "기술 서비스",
    indsSclsCd: "M10901",
    indsSclsNm: "건축 설계 및 관련 서비스업",
  },
  {
    indsMclsCd: "M109",
    indsMclsNm: "기술 서비스",
    indsSclsCd: "M10902",
    indsSclsNm: "도시 계획 및 조경 설계 서비스업",
  },
  {
    indsMclsCd: "M109",
    indsMclsNm: "기술 서비스",
    indsSclsCd: "M10903",
    indsSclsNm: "건물 및 토목 엔지니어링 서비스업",
  },
  {
    indsMclsCd: "M109",
    indsMclsNm: "기술 서비스",
    indsSclsCd: "M10904",
    indsSclsNm: "환경 관련 엔지니어링 서비스업",
  },
  {
    indsMclsCd: "M109",
    indsMclsNm: "기술 서비스",
    indsSclsCd: "M10999",
    indsSclsNm: "기타 엔지니어링 서비스업",
  },
  { indsMclsCd: "M111", indsMclsNm: "수의", indsSclsCd: "M11101", indsSclsNm: "동물병원" },
  {
    indsMclsCd: "M112",
    indsMclsNm: "전문 디자인",
    indsSclsCd: "M11201",
    indsSclsNm: "인테리어 디자인업",
  },
  {
    indsMclsCd: "M112",
    indsMclsNm: "전문 디자인",
    indsSclsCd: "M11202",
    indsSclsNm: "제품 디자인업",
  },
  {
    indsMclsCd: "M112",
    indsMclsNm: "전문 디자인",
    indsSclsCd: "M11203",
    indsSclsNm: "시각 디자인업",
  },
  {
    indsMclsCd: "M112",
    indsMclsNm: "전문 디자인",
    indsSclsCd: "M11204",
    indsSclsNm: "패션/섬유/기타 전문 디자인업",
  },
  { indsMclsCd: "M113", indsMclsNm: "사진 촬영", indsSclsCd: "M11301", indsSclsNm: "사진촬영업" },
  {
    indsMclsCd: "M114",
    indsMclsNm: "인쇄·제품제작",
    indsSclsCd: "M11401",
    indsSclsNm: "명함/간판/광고물 제작",
  },
  {
    indsMclsCd: "M115",
    indsMclsNm: "기타 전문 과학",
    indsSclsCd: "M11502",
    indsSclsNm: "번역/통역 서비스업",
  },
  {
    indsMclsCd: "M115",
    indsMclsNm: "기타 전문 과학",
    indsSclsCd: "M11504",
    indsSclsNm: "사업/무형 재산권 중개업",
  },
  {
    indsMclsCd: "N101",
    indsMclsNm: "시설관리",
    indsSclsCd: "N10101",
    indsSclsNm: "사업시설 유지·관리 서비스업",
  },
  {
    indsMclsCd: "N102",
    indsMclsNm: "청소·방제",
    indsSclsCd: "N10201",
    indsSclsNm: "건축물 일반 청소업",
  },
  {
    indsMclsCd: "N102",
    indsMclsNm: "청소·방제",
    indsSclsCd: "N10202",
    indsSclsNm: "산업설비, 운송장비 및 공공장소 청소업",
  },
  {
    indsMclsCd: "N102",
    indsMclsNm: "청소·방제",
    indsSclsCd: "N10203",
    indsSclsNm: "소독, 구충 및 방제 서비스업",
  },
  {
    indsMclsCd: "N103",
    indsMclsNm: "조경·유지",
    indsSclsCd: "N10301",
    indsSclsNm: "조경 유지·관리 서비스업",
  },
  { indsMclsCd: "N104", indsMclsNm: "고용 알선", indsSclsCd: "N10401", indsSclsNm: "고용 알선업" },
  {
    indsMclsCd: "N104",
    indsMclsNm: "고용 알선",
    indsSclsCd: "N10402",
    indsSclsNm: "임시/일용 인력 공급업",
  },
  {
    indsMclsCd: "N104",
    indsMclsNm: "고용 알선",
    indsSclsCd: "N10403",
    indsSclsNm: "상용 인력 공급 및 인사관리 서비스업",
  },
  { indsMclsCd: "N105", indsMclsNm: "여행사·보조", indsSclsCd: "N10501", indsSclsNm: "여행사" },
  {
    indsMclsCd: "N105",
    indsMclsNm: "여행사·보조",
    indsSclsCd: "N10599",
    indsSclsNm: "기타 여행 보조/예약 서비스업",
  },
  { indsMclsCd: "N107", indsMclsNm: "사무 지원", indsSclsCd: "N10703", indsSclsNm: "복사업" },
  {
    indsMclsCd: "N107",
    indsMclsNm: "사무 지원",
    indsSclsCd: "N10799",
    indsSclsNm: "기타 사무 지원 서비스업",
  },
  {
    indsMclsCd: "N108",
    indsMclsNm: "기타 사업 서비스",
    indsSclsCd: "N10802",
    indsSclsNm: "전시/컨벤션/행사 대행 서비스업",
  },
  {
    indsMclsCd: "N108",
    indsMclsNm: "기타 사업 서비스",
    indsSclsCd: "N10805",
    indsSclsNm: "포장/충전업",
  },
  {
    indsMclsCd: "N109",
    indsMclsNm: "운송장비 대여",
    indsSclsCd: "N10901",
    indsSclsNm: "자동차 대여업",
  },
  {
    indsMclsCd: "N109",
    indsMclsNm: "운송장비 대여",
    indsSclsCd: "N10999",
    indsSclsNm: "기타 운송장비 대여업",
  },
  {
    indsMclsCd: "N110",
    indsMclsNm: "가정용품 대여",
    indsSclsCd: "N11001",
    indsSclsNm: "스포츠/레크리에이션 용품 대여업",
  },
  {
    indsMclsCd: "N110",
    indsMclsNm: "가정용품 대여",
    indsSclsCd: "N11002",
    indsSclsNm: "음반/비디오물 대여업",
  },
  { indsMclsCd: "N110", indsMclsNm: "가정용품 대여", indsSclsCd: "N11003", indsSclsNm: "만화방" },
  {
    indsMclsCd: "N110",
    indsMclsNm: "가정용품 대여",
    indsSclsCd: "N11004",
    indsSclsNm: "의류 대여업",
  },
  {
    indsMclsCd: "N110",
    indsMclsNm: "가정용품 대여",
    indsSclsCd: "N11099",
    indsSclsNm: "기타 개인/가정용품 대여업",
  },
  {
    indsMclsCd: "N111",
    indsMclsNm: "산업용품 대여",
    indsSclsCd: "N11101",
    indsSclsNm: "건설기계/장비 대여업",
  },
  {
    indsMclsCd: "N111",
    indsMclsNm: "산업용품 대여",
    indsSclsCd: "N11102",
    indsSclsNm: "컴퓨터/사무기기 대여업",
  },
  {
    indsMclsCd: "N111",
    indsMclsNm: "산업용품 대여",
    indsSclsCd: "N11199",
    indsSclsNm: "기타 산업용 기계/장비 대여업",
  },
  {
    indsMclsCd: "P105",
    indsMclsNm: "일반 교육",
    indsSclsCd: "P10501",
    indsSclsNm: "입시·교과학원",
  },
  {
    indsMclsCd: "P106",
    indsMclsNm: "기타 교육",
    indsSclsCd: "P10601",
    indsSclsNm: "태권도/무술학원",
  },
  {
    indsMclsCd: "P106",
    indsMclsNm: "기타 교육",
    indsSclsCd: "P10603",
    indsSclsNm: "요가/필라테스 학원",
  },
  {
    indsMclsCd: "P106",
    indsMclsNm: "기타 교육",
    indsSclsCd: "P10605",
    indsSclsNm: "레크리에이션 교육기관",
  },
  {
    indsMclsCd: "P106",
    indsMclsNm: "기타 교육",
    indsSclsCd: "P10607",
    indsSclsNm: "청소년 수련시설",
  },
  { indsMclsCd: "P106", indsMclsNm: "기타 교육", indsSclsCd: "P10609", indsSclsNm: "음악학원" },
  { indsMclsCd: "P106", indsMclsNm: "기타 교육", indsSclsCd: "P10611", indsSclsNm: "미술학원" },
  {
    indsMclsCd: "P106",
    indsMclsNm: "기타 교육",
    indsSclsCd: "P10613",
    indsSclsNm: "기타 예술/스포츠 교육기관",
  },
  { indsMclsCd: "P106", indsMclsNm: "기타 교육", indsSclsCd: "P10615", indsSclsNm: "외국어학원" },
  {
    indsMclsCd: "P106",
    indsMclsNm: "기타 교육",
    indsSclsCd: "P10617",
    indsSclsNm: "전문자격/고시학원",
  },
  { indsMclsCd: "P106", indsMclsNm: "기타 교육", indsSclsCd: "P10619", indsSclsNm: "사회교육시설" },
  {
    indsMclsCd: "P106",
    indsMclsNm: "기타 교육",
    indsSclsCd: "P10621",
    indsSclsNm: "직원 훈련기관",
  },
  { indsMclsCd: "P106", indsMclsNm: "기타 교육", indsSclsCd: "P10623", indsSclsNm: "운전학원" },
  {
    indsMclsCd: "P106",
    indsMclsNm: "기타 교육",
    indsSclsCd: "P10625",
    indsSclsNm: "기타 기술/직업 훈련학원",
  },
  { indsMclsCd: "P106", indsMclsNm: "기타 교육", indsSclsCd: "P10627", indsSclsNm: "컴퓨터 학원" },
  {
    indsMclsCd: "P106",
    indsMclsNm: "기타 교육",
    indsSclsCd: "P10629",
    indsSclsNm: "그 외 기타 교육기관",
  },
  { indsMclsCd: "P107", indsMclsNm: "교육 지원", indsSclsCd: "P10701", indsSclsNm: "교육컨설팅업" },
  {
    indsMclsCd: "P107",
    indsMclsNm: "교육 지원",
    indsSclsCd: "P10799",
    indsSclsNm: "기타 교육지원 서비스업",
  },
  { indsMclsCd: "Q101", indsMclsNm: "병원", indsSclsCd: "Q10101", indsSclsNm: "종합병원" },
  { indsMclsCd: "Q101", indsMclsNm: "병원", indsSclsCd: "Q10102", indsSclsNm: "일반병원" },
  { indsMclsCd: "Q101", indsMclsNm: "병원", indsSclsCd: "Q10103", indsSclsNm: "치과병원" },
  { indsMclsCd: "Q101", indsMclsNm: "병원", indsSclsCd: "Q10104", indsSclsNm: "한방병원" },
  { indsMclsCd: "Q101", indsMclsNm: "병원", indsSclsCd: "Q10105", indsSclsNm: "요양병원" },
  { indsMclsCd: "Q102", indsMclsNm: "의원", indsSclsCd: "Q10201", indsSclsNm: "내과/소아과 의원" },
  { indsMclsCd: "Q102", indsMclsNm: "의원", indsSclsCd: "Q10202", indsSclsNm: "외과 의원" },
  { indsMclsCd: "Q102", indsMclsNm: "의원", indsSclsCd: "Q10203", indsSclsNm: "신경/정신과 의원" },
  {
    indsMclsCd: "Q102",
    indsMclsNm: "의원",
    indsSclsCd: "Q10204",
    indsSclsNm: "피부/비뇨기과 의원",
  },
  { indsMclsCd: "Q102", indsMclsNm: "의원", indsSclsCd: "Q10205", indsSclsNm: "안과 의원" },
  { indsMclsCd: "Q102", indsMclsNm: "의원", indsSclsCd: "Q10206", indsSclsNm: "이비인후과 의원" },
  { indsMclsCd: "Q102", indsMclsNm: "의원", indsSclsCd: "Q10207", indsSclsNm: "산부인과 의원" },
  { indsMclsCd: "Q102", indsMclsNm: "의원", indsSclsCd: "Q10208", indsSclsNm: "성형외과 의원" },
  { indsMclsCd: "Q102", indsMclsNm: "의원", indsSclsCd: "Q10209", indsSclsNm: "기타 의원" },
  { indsMclsCd: "Q102", indsMclsNm: "의원", indsSclsCd: "Q10210", indsSclsNm: "치과의원" },
  { indsMclsCd: "Q102", indsMclsNm: "의원", indsSclsCd: "Q10211", indsSclsNm: "한의원" },
  {
    indsMclsCd: "Q102",
    indsMclsNm: "의원",
    indsSclsCd: "Q10212",
    indsSclsNm: "방사선 진단/병리 검사 의원",
  },
  { indsMclsCd: "Q104", indsMclsNm: "기타 보건", indsSclsCd: "Q10402", indsSclsNm: "유사 의료업" },
  {
    indsMclsCd: "R102",
    indsMclsNm: "도서관·사적지",
    indsSclsCd: "R10202",
    indsSclsNm: "독서실/스터디 카페",
  },
  {
    indsMclsCd: "R103",
    indsMclsNm: "스포츠 서비스",
    indsSclsCd: "R10306",
    indsSclsNm: "종합 스포츠시설",
  },
  { indsMclsCd: "R103", indsMclsNm: "스포츠 서비스", indsSclsCd: "R10307", indsSclsNm: "헬스장" },
  { indsMclsCd: "R103", indsMclsNm: "스포츠 서비스", indsSclsCd: "R10308", indsSclsNm: "수영장" },
  { indsMclsCd: "R103", indsMclsNm: "스포츠 서비스", indsSclsCd: "R10309", indsSclsNm: "볼링장" },
  { indsMclsCd: "R103", indsMclsNm: "스포츠 서비스", indsSclsCd: "R10310", indsSclsNm: "당구장" },
  {
    indsMclsCd: "R103",
    indsMclsNm: "스포츠 서비스",
    indsSclsCd: "R10311",
    indsSclsNm: "골프 연습장",
  },
  { indsMclsCd: "R103", indsMclsNm: "스포츠 서비스", indsSclsCd: "R10312", indsSclsNm: "테니스장" },
  { indsMclsCd: "R103", indsMclsNm: "스포츠 서비스", indsSclsCd: "R10313", indsSclsNm: "탁구장" },
  {
    indsMclsCd: "R103",
    indsMclsNm: "스포츠 서비스",
    indsSclsCd: "R10314",
    indsSclsNm: "기타 스포츠시설 운영업",
  },
  {
    indsMclsCd: "R103",
    indsMclsNm: "스포츠 서비스",
    indsSclsCd: "R10316",
    indsSclsNm: "스쿼시/라켓볼장",
  },
  { indsMclsCd: "R104", indsMclsNm: "유원지·오락", indsSclsCd: "R10402", indsSclsNm: "비디오방" },
  {
    indsMclsCd: "R104",
    indsMclsNm: "유원지·오락",
    indsSclsCd: "R10404",
    indsSclsNm: "전자 게임장",
  },
  {
    indsMclsCd: "R104",
    indsMclsNm: "유원지·오락",
    indsSclsCd: "R10405",
    indsSclsNm: "기타 오락장",
  },
  { indsMclsCd: "R104", indsMclsNm: "유원지·오락", indsSclsCd: "R10406", indsSclsNm: "PC방" },
  { indsMclsCd: "R104", indsMclsNm: "유원지·오락", indsSclsCd: "R10407", indsSclsNm: "노래방" },
  {
    indsMclsCd: "R104",
    indsMclsNm: "유원지·오락",
    indsSclsCd: "R10408",
    indsSclsNm: "낚시터 운영업",
  },
  {
    indsMclsCd: "R104",
    indsMclsNm: "유원지·오락",
    indsSclsCd: "R10409",
    indsSclsNm: "수상/해양 레저업",
  },
  {
    indsMclsCd: "R104",
    indsMclsNm: "유원지·오락",
    indsSclsCd: "R10410",
    indsSclsNm: "복권 발행/판매업",
  },
  {
    indsMclsCd: "R104",
    indsMclsNm: "유원지·오락",
    indsSclsCd: "R10414",
    indsSclsNm: "바둑/장기/체스 경기 운영업",
  },
  {
    indsMclsCd: "R104",
    indsMclsNm: "유원지·오락",
    indsSclsCd: "R10499",
    indsSclsNm: "기타 오락관련 서비스업",
  },
  {
    indsMclsCd: "S201",
    indsMclsNm: "컴퓨터 수리",
    indsSclsCd: "S20101",
    indsSclsNm: "컴퓨터/노트북/프린터 수리업",
  },
  {
    indsMclsCd: "S202",
    indsMclsNm: "통신장비 수리",
    indsSclsCd: "S20201",
    indsSclsNm: "핸드폰/통신장비 수리업",
  },
  {
    indsMclsCd: "S203",
    indsMclsNm: "자동차 수리·세차",
    indsSclsCd: "S20301",
    indsSclsNm: "자동차 정비소",
  },
  {
    indsMclsCd: "S203",
    indsMclsNm: "자동차 수리·세차",
    indsSclsCd: "S20302",
    indsSclsNm: "자동차 세차장",
  },
  {
    indsMclsCd: "S204",
    indsMclsNm: "모터사이클 수리",
    indsSclsCd: "S20401",
    indsSclsNm: "모터사이클 수리업",
  },
  {
    indsMclsCd: "S205",
    indsMclsNm: "가전제품 수리",
    indsSclsCd: "S20501",
    indsSclsNm: "가전제품 수리업",
  },
  {
    indsMclsCd: "S206",
    indsMclsNm: "기타 가정용품 수리",
    indsSclsCd: "S20601",
    indsSclsNm: "의류/이불 수선업",
  },
  {
    indsMclsCd: "S206",
    indsMclsNm: "기타 가정용품 수리",
    indsSclsCd: "S20602",
    indsSclsNm: "가죽/가방/신발 수선업",
  },
  {
    indsMclsCd: "S206",
    indsMclsNm: "기타 가정용품 수리",
    indsSclsCd: "S20603",
    indsSclsNm: "시계/귀금속/악기 수리업",
  },
  {
    indsMclsCd: "S206",
    indsMclsNm: "기타 가정용품 수리",
    indsSclsCd: "S20699",
    indsSclsNm: "그 외 기타 개인/가정용품 수리업",
  },
  { indsMclsCd: "S207", indsMclsNm: "이용·미용", indsSclsCd: "S20701", indsSclsNm: "미용실" },
  { indsMclsCd: "S207", indsMclsNm: "이용·미용", indsSclsCd: "S20702", indsSclsNm: "피부 관리실" },
  { indsMclsCd: "S207", indsMclsNm: "이용·미용", indsSclsCd: "S20703", indsSclsNm: "네일숍" },
  {
    indsMclsCd: "S208",
    indsMclsNm: "욕탕·신체관리",
    indsSclsCd: "S20801",
    indsSclsNm: "목욕탕/사우나",
  },
  {
    indsMclsCd: "S208",
    indsMclsNm: "욕탕·신체관리",
    indsSclsCd: "S20802",
    indsSclsNm: "마사지/안마",
  },
  {
    indsMclsCd: "S208",
    indsMclsNm: "욕탕·신체관리",
    indsSclsCd: "S20803",
    indsSclsNm: "체형/비만 관리",
  },
  { indsMclsCd: "S209", indsMclsNm: "세탁", indsSclsCd: "S20901", indsSclsNm: "세탁소" },
  { indsMclsCd: "S209", indsMclsNm: "세탁", indsSclsCd: "S20902", indsSclsNm: "셀프 빨래방" },
  { indsMclsCd: "S210", indsMclsNm: "장례식장 ", indsSclsCd: "S21001", indsSclsNm: "장례식장" },
  {
    indsMclsCd: "S210",
    indsMclsNm: "장례식장 ",
    indsSclsCd: "S21002",
    indsSclsNm: "화장터/묘지/납골당",
  },
  { indsMclsCd: "S211", indsMclsNm: "기타 개인", indsSclsCd: "S21101", indsSclsNm: "예식장업" },
  {
    indsMclsCd: "S211",
    indsMclsNm: "기타 개인",
    indsSclsCd: "S21105",
    indsSclsNm: "결혼 상담 서비스업",
  },
] as const satisfies readonly IndustryCategory[];
export type MiddleCategory = { code: string; name: string };
const VISIT_FOCUSED_MIDDLE_CODES = [
  "I201", // 한식
  "I202", // 중식
  "I203", // 일식
  "I204", // 서양식
  "I205", // 기타 음식점
  "I212", // 카페
  "I211", // 주점
  "S207", // 미용
] as const;

export const getMiddleCategories = (): MiddleCategory[] => {
  const categories = Array.from(
    new Map(
      INDUSTRY_CATEGORIES.map((item) => [
        item.indsMclsCd,
        { code: item.indsMclsCd, name: item.indsMclsNm },
      ]),
    ).values(),
  );

  return categories.sort((a, b) => {
    const aIndex = VISIT_FOCUSED_MIDDLE_CODES.indexOf(a.code as (typeof VISIT_FOCUSED_MIDDLE_CODES)[number]);
    const bIndex = VISIT_FOCUSED_MIDDLE_CODES.indexOf(b.code as (typeof VISIT_FOCUSED_MIDDLE_CODES)[number]);
    const aPriority = aIndex === -1 ? VISIT_FOCUSED_MIDDLE_CODES.length : aIndex;
    const bPriority = bIndex === -1 ? VISIT_FOCUSED_MIDDLE_CODES.length : bIndex;
    return aPriority - bPriority;
  });
};
export const getSmallCategories = (middleCode: string) =>
  INDUSTRY_CATEGORIES.filter((item) => item.indsMclsCd === middleCode);
export const getCategoryBySmallCode = (smallCode: string) =>
  INDUSTRY_CATEGORIES.find((item) => item.indsSclsCd === smallCode);
export const isValidCategoryPath = (middleCode: string, smallCode: string) =>
  INDUSTRY_CATEGORIES.some(
    (item) => item.indsMclsCd === middleCode && item.indsSclsCd === smallCode,
  );
